["dist/demo_bundled.js"]
deps=[
    "webpack.config.cjs",
    "src/demo.js",
    "src/index.js",
    "src/color.js",
    "src/random.js",
    "src/optimizer.js"]
exec="npx webpack --mode=production --config=webpack.config.cjs"
#exec="npx webpack --mode=development --devtool=inline-source-map"

["serve"]
deps=["dist/demo_bundled.js"]
exec="cd dist && python -m SimpleHTTPServer 8888"

["clean"]
exec="rm dist/demo_bundled.js"